/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */
 /*
 
public void slider2d1_change1(GSlider2D source, GEvent event) { //_CODE_:slider2d1:668017:
  println("slider2d1 - GSlider2D >> GEvent." + event + " @ " + millis());
} //_CODE_:slider2d1:668017:

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:window1:993686:
  appc.background(230);
} //_CODE_:window1:993686:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:702096:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:702096:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(true);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  slider2d1 = new GSlider2D(this, 8, 8, 50, 50);
  slider2d1.setLimitsX(0.5, 0.0, 1.0);
  slider2d1.setLimitsY(0.5, 0.0, 1.0);
  slider2d1.setNumberFormat(G4P.DECIMAL, 2);
  slider2d1.setOpaque(true);
  slider2d1.addEventHandler(this, "slider2d1_change1");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw2");
  button1 = new GButton(window1, 80, 45, 80, 30);
  button1.setText("Face text");
  button1.addEventHandler(this, "button1_click1");
  view1 = new GView(window1, 40, 16, 152, 88, JAVA2D);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GSlider2D slider2d1; 
GWindow window1;
GButton button1; 
GView view1; 
*/
